
services:
  backend:
    build: ./backend
    networks:
      - ecom_network
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/requirements.txt

  frontend:
    build: ./frontend
    networks:
      - ecom_network
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .angular/
            - dist/
        - action: rebuild
          path: ./frontend/package.json
  nginx:
    build: ./nginx
    networks:
      - ecom_network
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:15-alpine
    networks:
      - ecom_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  ecom_network:
    driver: bridge

volumes:
  postgres_data:

